version: '3'
services:
  iurleite:
    build: ../iurleite/
    restart: always
    ports:
      - 8080:80
  buszinga:
    build: ../buszinga/
    restart: always
    ports:
      - 8081:80

  master:
    image: nginx
    ports:
      - 8082:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./servers:/var/servers
    restart: always
    depends_on:
      - iurleite
      - buszinga
