version: '3'
services:
  webserver:
    image: nginx
    ports:
      - 8082:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./servers:/var/servers
  iurleite:
    build: ../iurleite/
    ports:
      - 8080:80
  buszinga:
    build: ../buszinga/
    ports:
      - 8081:80
