version: '2'
services:
  iurleite:
    build: ../iurleite/
    restart: always
    networks:
      - main

  buszinga:
    build: ../buszinga/
    restart: always
    networks:
      - main

  master:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./servers:/var/servers
    restart: always
    depends_on:
      - iurleite
      - buszinga
    networks:
      - main

networks:
  main:
    driver: bridge
